ALTER TABLE `appbanco`.`CURSOS_ASIGNATURAS` 
ADD INDEX `id_asignatura_curso_idx` (`ID_ASIGNATURA` ASC);
ALTER TABLE `appbanco`.`CURSOS_ASIGNATURAS` 
ADD CONSTRAINT `id_asignatura_curso`
  FOREIGN KEY (`ID_ASIGNATURA`)
  REFERENCES `appbanco`.`ASIGNATURAS` (`ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;
