ALTER TABLE `appbanco`.`ASIGNATURA_UNIDADTRABAJO` 
ADD INDEX `ID_ASIG_UNIDAD_idx` (`ID_ASIGNATURA` ASC);
ALTER TABLE `appbanco`.`ASIGNATURA_UNIDADTRABAJO` 
ADD CONSTRAINT `ID_ASIG_UNIDAD`
  FOREIGN KEY (`ID_ASIGNATURA`)
  REFERENCES `appbanco`.`ASIGNATURAS` (`ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;
