      <footer>
        <div class="contenedor">
          <a title="Erastus Maximus" href="https://www.w3schools.com"><img alt="W3Schools" src="/img/Erastus.jpeg"></a>
          <a title="Epic fail" href="https://www.w3schools.com"><img alt="W3Schools" src="/img/dominos.jpg"></a>
            <a title="Andrei Estuvo Aqui" href="https://www.w3schools.com"><img alt="W3Schools"
                                                                                src="/img/trollface.jpg"></a>
          <a title="Está pocho" href="https://www.w3schools.com"><img alt="W3Schools" src="/img/caducamadrid.jpg"></a>
          <a href="https://www.w3schools.com"><img alt="W3Schools" src="/img/madrid.jpg"></a>
          <p class="copy"><br>Web realizada por los alumnos de 2º de DAW del curso 2017-18</p>
        </div>
      </footer>

