    <header id="header">
        <div class="contenedor">
          <div class="anagrama">
            <img alt="logo" src="/img/logo.png">
          </div>
          <h3>I.E.S. Enrique Tierno Galván</h3>
          <div class="bandera"> 
              <img alt="España" src="/img/Spain.png">
              <img alt="UK" src="/img/United.png">
          </div>
        </div>
    </header>    

