
    
    <nav class="navbar navbar-inverse">
        <div class="contenedor">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">WebSiteName</a>
    </div>
    <ul class="nav navbar-nav">
        <li class="active"><a href="#">Home</a></li>
        <li><a href="index.html" target="_blank">Contabilidad</a></li>
        <li><a href="/index.php?c=maintenance">Incidencias TIC</a></li>
        <li><a href="index.html" target="_blank">Documentos</a></li>
        <li><a href="index.html" target="_blank">Programaciones</a></li>
        <li><a href="/index.php?c=venta_libros">Libros 2ª mano</a></li>
        <li><a href="/index.php?c=tareas">Tareas para alumnos</a></li>
        <li><a href="index.php?c=bolsa_trabajo">Bolsa de Trabajo</a></li>
    </ul>
      </nav>
  </div>

</div>

