<div class="contenedor">
    <nav class="navbar navbar-expand-md bg-dark navbar-dark colorMenu">
        <div class="container">
            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbar3SupportedContent">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse text-center justify-content-center" id="navbar3SupportedContent">
                <ul class="navbar-nav">
                    <li class="nav-item"><a class="nav-link" href="#">Home</a></li>
                    <li class="nav-item"><a class="nav-link" href="index.html" target="_blank">Contabilidad</a></li>
                    <li class="nav-item"><a class="nav-link" href="/index.php?c=maintenance">Incidencias TIC</a></li>
                    <li class="nav-item"><a class="nav-link" href="index.html" target="_blank">Documentos</a></li>
                    <li class="nav-item"><a class="nav-link" href="index.html" target="_blank">Programaciones</a></li>
                    <li class="nav-item"><a class="nav-link" href="/index.php?c=venta_libros">Libros 2ª mano</a></li>
                    <li class="nav-item"><a class="nav-link" href="/index.php?c=tareas">Tareas para alumnos</a></li>
                    <li class="nav-item"><a class="nav-link" href="index.php?c=bolsa_trabajo">Bolsa de Trabajo</a></li>
                    <li class="nav-item"><a class="nav-link" href="index.php?c=crud_users">Crud Users</a></li>
                </ul>
            </div>
        </div>
    </nav>

</div>

