      <div class="contenedor">
        <label id="btn-menu" ><img alt="img-menu" src="img/menu.png"></label>
        <nav class="menu" id="nav">
          <ul>
            <li><a href="index.html" target="_blank">Contabilidad</a></li>
            <li><a href="index.html" target="_blank">Incidencias TIC</a></li>
            <li><a href="index.html" target="_blank">Documentos</a></li>
            <li><a href="index.html" target="_blank">Programaciones</a></li>
            <li><a href="index.html" target="_blank">Libros 2ª mano</a></li>
            <li><a href="index.html" target="_blank">Tareas para alumnos</a></li>
          </ul>
        </nav>
      </div>

